Dmitriy zhdanovich lesson 11 2
alexander-sidorov/m-pt1-63-23 pull request #146
Opened 2023-04-11 14:02 UTC by Mitya890625

closes #136

2023-04-12 11:52 UTC, Mitya890625 commented on services/webapp/hw/dmitriy_zhdanovich/contacts.py
Привет Саша, не совсем понятно каким образом body запроса POST постмана попадает в метод handle модуля contacts. То же самое с PATCH. Смотрел разные источники, но там работают уже с готовыми фреймворками и для этих случаев они используют декораторы с уже реализованной логикой.

2023-04-12 11:58 UTC, alexander-sidorov commented on services/webapp/hw/dmitriy_zhdanovich/contacts.py
Митя, пример: ты отправляешь запрос:

```bash
poetry run http -v post http://localhost:8000/~/dmitriy_zhdanovich/contacts name=a phone=b
```

в этот момент, допустим, сервер вызывает функцию `hw.dmitriy_zhdanovich.contacts.handler`, так? Передаёт аргументом объект типа `framework.http.Request`, так? А что в этом объекте есть, посмотри дебагом или принтами — там в этот момент есть `request.body`? что в нём написано?

2023-04-14 12:34 UTC, Mitya890625 commented on services/webapp/hw/dmitriy_zhdanovich/contacts.py
Привет Саш, 
1. Не проходят тесты post и patch, для того чтоб они прошли необходимо подключать базы данных и сохранять добавленные контакты чтобы методы PATCH и POST сущности web_client могли проверить добавились или проапгрейдились данные, я правильно понимаю? 
2. Тесты get_all_contacts и get_one_contact проходят локально(task run-tests) а вот у тебя крашатся, причина для меня загадочна, прольешь немного света не нее?)

2023-04-14 14:27 UTC, alexander-sidorov commented on services/webapp/hw/dmitriy_zhdanovich/contacts.py
@Mitya890625 Митя,

> Не проходят тесты post и patch

сейчас достаточно сделать так, чтобы такие запросы было возможно выполнить технически, и сервер на них отвечал 201 и 200 соответственно, присылая какую-нибудь инфу в body

> Тесты get_all_contacts и get_one_contact проходят локально(task run-tests) а вот у тебя крашатся, причина для меня загадочна, прольешь немного света не нее?)

В логах, кроме 500 статуса, нету ничего - будем запускать на занятии и дебажить

2023-04-14 21:34 UTC, alexander-sidorov requested changes

2023-04-14 21:34 UTC, alexander-sidorov commented on services/webapp/tests/integration/hw/dmitriy_zhdanovich/test_routing.py
> +    assert resp.status_code == 500
надо разобраться, не должно быть 500 ошибки ни на какой запрос. 500 означает что сервер умер: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500)

2023-04-15 04:16 UTC, Mitya890625 commented on services/webapp/tests/integration/hw/dmitriy_zhdanovich/test_routing.py
> +    assert resp.status_code == 500
Это проверка на несуществующий метод данного типа. В коде я кидаю эксепшн ValueError и сервер в ASGI.py ловит Exception и возвращает джсон {"exception": ..., "tb": ... } выдавая ошибку 500. Если так не должно быть значит я неправильно понял реализацию эксепшнов )

2023-04-15 12:26 UTC, alexander-sidorov requested changes

2023-04-15 12:26 UTC, alexander-sidorov commented on services/webapp/hw/dmitriy_zhdanovich/contacts.py
> +        user_id = int(path_list[4])
Запускаю сервер, делаю запрос на чтение всех контактов и получаю ошибку:

```python
Traceback (most recent call last):
  File \"/Users/alex/projects/itacademy/m-pt1-63-23/services/webapp/./webapp/asgi.py\", line 62, in application
    response = main(request)
  File \"/Users/alex/projects/itacademy/m-pt1-63-23/services/webapp/./hw/dmitriy_zhdanovich/routing.py\", line 25, in main
    return handler(request)
  File \"/Users/alex/projects/itacademy/m-pt1-63-23/services/webapp/./hw/dmitriy_zhdanovich/contacts.py\", line 34, in handler
    user_id = int(path_list[4])
IndexError: list index out of range
```

она говорит о том, что:
1. чтение всех контактов должно работать при запросе на `/contacts`, а не на `/contacts/`
2. или чтение всех контактов должно работать при запросе на ОБА таких урла
3. и перед тем, как индексировать список, надо убедиться, что индекс там есть)

2023-04-15 12:26 UTC, alexander-sidorov commented on services/webapp/hw/dmitriy_zhdanovich/contacts.py
> +        body_1 = dict(json.loads(request.body.decode()))
1. `json.loads` умеет  работать и с байтами
2. если в аргументе будет валидный json-объект, то он десериализуется в словарь сразу, без конверсии `dict(...)`:

```python
In [2]: json.loads(b'{"a": "b"}')
Out[2]: {'a': 'b'}
```

2023-04-15 12:26 UTC, alexander-sidorov commented on services/webapp/hw/dmitriy_zhdanovich/contacts.py
> +        new_contact: Contact = Contact(
```python
new_contact = Contact.parse_raw(request.body)
```

2023-04-15 12:26 UTC, alexander-sidorov commented on services/webapp/hw/dmitriy_zhdanovich/contacts.py
> +        contacts.items[user_id] = updated_contact
Отправляю запрос:

```python
import requests
import json

url = "http://localhost:8000/~/dmitriy_zhdanovich/contacts/1212"

payload = json.dumps({
  "phone": "123"
})
headers = {
  'Content-Type': 'application/json'
}

response = requests.request("PATCH", url, headers=headers, data=payload)

print(response.text)

```

Получаю 500 ошибку:

```python
Traceback (most recent call last):
  File \"/Users/alex/projects/itacademy/m-pt1-63-23/services/webapp/./webapp/asgi.py\", line 62, in application
    response = main(request)
  File \"/Users/alex/projects/itacademy/m-pt1-63-23/services/webapp/./hw/dmitriy_zhdanovich/routing.py\", line 25, in main
    return handler(request)
  File \"/Users/alex/projects/itacademy/m-pt1-63-23/services/webapp/./hw/dmitriy_zhdanovich/contacts.py\", line 53, in handler
    contacts.items[user_id] = updated_contact
IndexError: list assignment index out of range

```

если ты используешь `contact_id` как индекс в списке, то не доверяй данным от пользователя — проверяй: если такого индекса нет, то сервер не должен умирать с 500 ошибкой, а показывать 404 - это ведь по сути ссылка на несуществующий контакт

2023-04-15 12:30 UTC, alexander-sidorov commented on services/webapp/tests/integration/hw/dmitriy_zhdanovich/test_routing.py
> +    assert resp.status_code == 500
Смотри, ошибка `500` говорит о том, что сервер сломался. То есть – таких ошибок быть не должно)

Если пользователь прислал хороший запрос, сервер должен его обработать и ответить кодом `2хх`.

Если пользователь прислал плохой запрос, сервер должен его НЕ обрабатывать и ответить кодом `4хх`.

А коды `5хх` означают, что косяк на нашей стороне) значит, надо чинить)

> несуществующий метод данного типа
если серверу не нравится метод клиента (GET/POST/... не там где надо), сервер может ответить одним из кодов:
- 400 [Bad Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400)
- 404 [Not Found](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404)
- 405 [Method Not Allowed](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405)
- 422 [Unprocessable Entity](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422)

2023-04-15 12:49 UTC, Mitya890625 commented on services/webapp/tests/integration/hw/dmitriy_zhdanovich/test_routing.py
> +    assert resp.status_code == 500
Понял, зачиню в скором времени

2023-04-18 19:27 UTC, alexander-sidorov requested changes

2023-04-18 19:27 UTC, alexander-sidorov commented on services/webapp/tests/integration/hw/dmitriy_zhdanovich/test_contacts.py
> +    resp: httpx.Response = await web_client.delete(url)
тут удаляется контакт, который не существует и так, правильно понимаю?

2023-04-18 19:27 UTC, alexander-sidorov commented on services/webapp/tests/integration/hw/dmitriy_zhdanovich/test_contacts.py
> +    url: str = "/~/dmitriy_zhdanovich/contacts/0",
перенеси, пожалуйста, `url` внутри самого теста, или сделай [pytest фикстурой](https://docs.pytest.org/en/6.2.x/fixture.html#back-to-fixtures)

2023-04-18 19:27 UTC, alexander-sidorov commented on services/webapp/tests/integration/hw/dmitriy_zhdanovich/test_contacts.py
> +    assert json.dumps({"title": "Contact updated", "status": True})
эта проверка проверяет что библиотека `json` работает, а зачем это проверять?

2023-04-18 19:27 UTC, alexander-sidorov commented on services/webapp/tests/integration/hw/dmitriy_zhdanovich/test_contacts.py
> +        url, content=json.dumps(updated_contact)
здесь патчится несуществующий контакт, правильно понимаю?

2023-04-18 19:27 UTC, alexander-sidorov commented on services/webapp/tests/integration/hw/dmitriy_zhdanovich/test_contacts.py
> +    assert resp.status_code == 200
так а какие контакты клиент получит, если сделает такой запрос? пустые? какие-то?

2023-04-18 19:27 UTC, alexander-sidorov commented on services/webapp/tests/integration/hw/dmitriy_zhdanovich/test_contacts.py
> +    url: str = "/~/dmitriy_zhdanovich/contacts/1341",
по тестам вообще неочевидно, почему контакт с `id=0` существует, а с `id=1341` — нет)

2023-04-18 19:51 UTC, Mitya890625 commented on services/webapp/tests/integration/hw/dmitriy_zhdanovich/test_contacts.py
> +    resp: httpx.Response = await web_client.delete(url)
здесь удаляется контакт с ид= 0 )

2023-04-19 07:10 UTC, Mitya890625 commented
А можешь поставить 7 и влить этот код в мейн? Хочу обновиться с мейном и 13 успеть сделать

2023-04-19 07:25 UTC, alexander-sidorov commented on services/webapp/tests/integration/hw/dmitriy_zhdanovich/test_contacts.py
> +    resp: httpx.Response = await web_client.delete(url)
понимаю, что делается запрос на удаление контакта с id=0
но, а он существовал, что его удаляют?
или можно удалять несуществующее?
или ?

2023-04-19 07:29 UTC, alexander-sidorov commented
> А можешь поставить 7 и влить этот код в мейн? Хочу обновиться с мейном и 13 успеть сделать

могу, но за 13 уже только, по 11-2 дедлайн прошёл ведь

а за 13, для 7/10, нужно как минимум следующее:

- [ ] можно прочитать все контакты
- [ ] можно прочитать конкретный контакт по его ИД
- [ ] можно создать новый контакт и затем увидеть его в списке всех контактов, и получить его по ИД
- [ ] можно обновить данные контакта и затем увидеть новые значения в списке всех контактов, и получить их по ИД
- [ ] можно удалить контакт по его ИД и затем убедиться, что контакт не показывается в списке всех контактов, а также его нельзя получить по его ИД

если тебе отдельная ветка, новая, нужна, то вмержи сам этот ПР, просто за него не получится заработать баллы)

2023-04-19 07:29 UTC, alexander-sidorov approved these changes

2023-04-19 07:30 UTC, Mitya890625 commented on services/webapp/tests/integration/hw/dmitriy_zhdanovich/test_contacts.py
> +    resp: httpx.Response = await web_client.delete(url)
Да, по автотестам я сначала создаю контакт, потом читаю все контакты, потом читаю контакт с ид 0, потом патчу его и удаляю, два последних автотеста проверяют неподдерживающиеся запросы

2023-04-19 07:51 UTC, merged