Maksim Berezovik Django app
alexander-sidorov/m-pt1-63-23 pull request #185
Opened 2023-05-01 15:33 UTC by MaksimBerezovik

Django app created 
closes #178

2023-05-02 11:45 UTC, alexander-sidorov requested changes

2023-05-02 11:45 UTC, alexander-sidorov commented on services/webapp/project/urls.py
> +    path("maksim_berezovik/", include("app_maksim_berezovik.urls")),
`m` > `l` по алфавиту

2023-05-02 11:56 UTC, MaksimBerezovik commented on services/webapp/project/urls.py
> +    path("maksim_berezovik/", include("app_maksim_berezovik.urls")),
Поправил

2023-05-02 11:56 UTC, MaksimBerezovik commented on services/webapp/index.html.1
> +293
удалил

2023-05-02 11:56 UTC, MaksimBerezovik commented on services/webapp/index.html
> +293
удалил

2023-05-02 11:57 UTC, MaksimBerezovik commented on services/webapp/pyproject.toml
> +include = '\.pyi?$'
видимо перепутал файл pyproject.toml со своим, не там удалил.

2023-05-03 16:08 UTC, alexander-sidorov submitted a review, later dismissed

2023-05-03 17:39 UTC, alexander-sidorov approved these changes

2023-05-03 17:39 UTC, merged