Maksim berezovik lesson05
alexander-sidorov/m-pt1-63-23 pull request #54
Opened 2023-03-17 18:48 UTC by MaksimBerezovik

2023-03-18 13:09 UTC, MaksimBerezovik commented
Привет, падает 2 теста из-за кода других студентов.
 Как это поправить?

2023-03-18 13:38 UTC, tgrx commented
> Привет, падает 2 теста из-за кода других студентов.
> Как это поправить?

Точно, я и забыл. Спасибо! Если твои задачи в задании все остальные выполнены, и твой код в порядке, я вмержу и так

2023-03-18 13:44 UTC, MaksimBerezovik commented
> 

mypy и pytest проходят

2023-03-18 13:55 UTC, alexander-sidorov requested changes
@MaksimBerezovik добавь пожалуйста тесты на случай, когда в запросе

- есть
- есть, но нет нужных

query params

2023-03-18 14:26 UTC, MaksimBerezovik commented
> 

Добавил

2023-03-18 14:30 UTC, MaksimBerezovik commented
> @MaksimBerezovik добавь пожалуйста тесты на случай, когда в запросе
> 
>     * есть
> 
>     * есть, но нет нужных
> 
> 
> query params

Добавил

2023-03-18 14:32 UTC, alexander-sidorov requested changes

2023-03-18 14:32 UTC, alexander-sidorov commented on services/webapp/tests/integration/hw/maksim_berezovik/test_lesson03.py
> +    assert "Hello nnnn from Maksim Berezovik" not in resp.text
попрошу вот этот тест расширить:

то что `"Hello nnn..."` **не будет** в тексте ответа, принято. Но — а что тогда будет? ошибка? отладочная инфа? Hello world? 

добавь пожалуйста эту проверку: что, в случае `GET /~/maksim_berezovik/?nnnn` сервер ответит - что?

и еще запусти плз в конце `task code-format`

2023-03-18 16:03 UTC, MaksimBerezovik commented on services/webapp/tests/integration/hw/maksim_berezovik/test_lesson03.py
> +    assert "Hello nnnn from Maksim Berezovik" not in resp.text
> попрошу вот этот тест расширить:
> 
> то что `"Hello nnn..."` **не будет** в тексте ответа, принято. Но — а что тогда будет? ошибка? отладочная инфа? Hello world?
> 
> добавь пожалуйста эту проверку: что, в случае `GET /~/maksim_berezovik/?nnnn` сервер ответит - что?
> 
> и еще запусти плз в конце `task code-format`
 
Добавил, code-format выполнинл.

2023-03-18 16:41 UTC, alexander-sidorov requested changes

2023-03-18 16:41 UTC, alexander-sidorov commented on services/webapp/tests/integration/hw/maksim_berezovik/test_lesson03.py
> +    assert "What?" in resp.text
конфликтует с пунктом 2 из задания

2023-03-18 16:53 UTC, MaksimBerezovik commented on services/webapp/tests/integration/hw/maksim_berezovik/test_lesson03.py
> +    assert "What?" in resp.text
Тест должен проверить нет ли в ответе "Hello nnn from Maksim Berezovik" и отвечает ли сервер "What?". Верно?

2023-03-18 16:59 UTC, alexander-sidorov commented on services/webapp/tests/integration/hw/maksim_berezovik/test_lesson03.py
> +    assert "What?" in resp.text
нигде в задании про ответ `"What?"` на `GET /~/maksim_berezovik` не написано)

2023-03-18 17:12 UTC, MaksimBerezovik commented on services/webapp/tests/integration/hw/maksim_berezovik/test_lesson03.py
> +    assert "What?" in resp.text
Тогда я не понял эту строчку
`добавь пожалуйста эту проверку: что, в случае GET /~/maksim_berezovik/?nnnn сервер ответит - что?`
Сервер должен в ответ посылать словарь scope, т.е. такой же ответ как в случае GET http://localhost:8000?

2023-03-18 17:15 UTC, MaksimBerezovik commented on services/webapp/tests/integration/hw/maksim_berezovik/test_lesson03.py
> +    assert "What?" in resp.text
Тогда получается, что есть ответ от сервера, и нету в ответе "Hello nnnn from Maksim Berezovik".

2023-03-18 17:55 UTC, tgrx commented on services/webapp/tests/integration/hw/maksim_berezovik/test_lesson03.py
> +    assert "What?" in resp.text
Смотри, если сделать GET запрос на /~/maksim_berezovik?nnnn, то путь запроса будет:
/~/maksim_berezovik
И это попадает под п.2 задания

а вот если запрос будет на 
/~/maksim_berezovik?name=x

то это уже п.3

2023-03-19 07:26 UTC, MaksimBerezovik commented
Привет, переделал тест.
Уточню по заданию:
1.  Если сделать GET запрос, то сервер отвечает HTTP ответом с текстом "Hello from Maksim Berezovik"
сервер отвечает на оба базовых `URL /~/maksim_berezovik` или` /~/maksim_berezovik/ `(скрин 1 и 2)
2. Если сделать GET запрос с query params, среди которых есть параметр name, то сервер отвечает HTTP ответом с текстом `"Hello {value} from Maksim Berezovik"`, где вместо `{value}` будет значение из query-параметра `name`(скрин 3)
3. Проверка автотестами.
3.1`async def test_lesson03_happy_query_1` - проверяет ответ сервера в `query-параметра `которого есть `name=Vika`  с базовым` URL: /~/maksim_berezovik/`
3.2`async def test_lesson03_happy_query_2` - проверяет ответ сервера в `query-параметра `которого есть `name=Vika`  с базовым` URL: /~/maksim_berezovik`

2023-03-19 10:47 UTC, alexander-sidorov commented
@MaksimBerezovik Максим,

>     Правильно понял?
да, но отчасти:

> 3\. 3.3 `async def test_lesson03_fail_query_1` - проверяет, что сервер отвечает и в ответе сервера нету`"Hello nnn from Maksim Berezovik"`, с базовым` URL: /~/maksim_berezovik/`
>     3..4`async def test_lesson03_fail_query_2` - проверяет, что сервер отвечает и в ответе сервера нету`"Hello nnn from Maksim Berezovik" с базовым` URL: /~/maksim_berezovik`.


Это так, но я подсвечиваю логический момент: то, что строки `"Hello nnn from Maksim Berezovik"` **нету** - это понятно, но какой смысл в существовании такого теста? А почему именно эту строку используешь? Почему не проверяешь, что строки `"Lorem ipsum"` нету? А `"в траве сидел кузнечик"`? Так можно проверять до бесконечности, поэтому проверка **отсутствия** чего-то — это хорошо, но не несёт много смысла без проверки на **присутствие** ожидаемого результата.

То есть, по заданию, на гет запрос на твой путь сервер должен отвечать `"Hello from Maksim Berezovik"`. А если есть name=XXX в query, то отвечать `"Hello XXX from Maksim Berezovik"`. Вот это и надо проверять:

```python
url = "/~/maksim_berezovik"
assert get(url) == "Hello from Maksim Berezovik"
assert get(url + "?nnn") == "Hello from Maksim Berezovik"
assert get(url + "?a=b&c=d") == "Hello from Maksim Berezovik"
assert get(url + "?name=XXX") == "Hello XXX from Maksim Berezovik"
```

в подобном подходе будет очевидно: на какой запрос будет какая реакция.

Бывают конечно случаи, когда **ожидаемый** результат очень громоздкий, но 1) это не тот случай, и 2) если даже и тот, то лучше проверить **ожидаемый** результат частично, чем проверять отсутствие **неожиданного**.

2023-03-19 11:00 UTC, MaksimBerezovik commented
Понял, т.е при наличии в query_request name=XXX сервер отвечает "Hello XXX from Maksim Berezovik". Во всех остальных случаях ответ "Hello from Maksim Berezovik "?

2023-03-19 12:04 UTC, MaksimBerezovik commented
Понял, т.е при наличии в query_request name=XXX сервер отвечает "Hello XXX from Maksim Berezovik". Во всех остальных случаях ответ "Hello from Maksim Berezovik "?

2023-03-19 13:16 UTC, alexander-sidorov commented
> Понял, т.е при наличии в query_request name=XXX сервер отвечает "Hello XXX from Maksim Berezovik". Во всех остальных случаях ответ "Hello from Maksim Berezovik "?

во всех остальных, но при условии, что запрос пришёл на путь `/~/maksim/berezovik` )

2023-03-19 16:43 UTC, MaksimBerezovik commented
> > Понял, т.е при наличии в query_request name=XXX сервер отвечает "Hello XXX from Maksim Berezovik". Во всех остальных случаях ответ "Hello from Maksim Berezovik "?
> 
> во всех остальных, но при условии, что запрос пришёл на путь `/~/maksim/berezovik` )

Поправил, посмотри пожалуйста.

2023-03-19 17:11 UTC, alexander-sidorov requested changes

2023-03-19 17:11 UTC, alexander-sidorov commented on services/webapp/hw/maksim_berezovik/lesson03.py
> +        if qd[0] != "":
условие `qd[0] == "name"` — частный случай `qd[0] != ""`

но в коде обрабатывается только этот частный случай.

поэтому более общая проверка - `qd[0] != ""` — здесь излишняя, вводит в заблуждение

2023-03-19 17:28 UTC, MaksimBerezovik commented on services/webapp/hw/maksim_berezovik/lesson03.py
> +        if qd[0] != "":
Поправил.

2023-03-19 19:05 UTC, alexander-sidorov approved these changes

2023-03-19 19:06 UTC, merged