Maksim berezovik lesson 5 2
alexander-sidorov/m-pt1-63-23 pull request #85
Opened 2023-03-22 17:24 UTC by MaksimBerezovik

close #70

2023-03-22 20:34 UTC, alexander-sidorov requested changes
Максим, твой код не проходит только проверку линтеров, поэтому предложу вот что:

1. в файл `services/webapp/hw/maksim_berezovik/lesson03.py` в строку 6 в конец её добавь комментарий: `# noqa: CCR001`
2. [остальные замечания тут](https://github.com/alexander-sidorov/m-pt1-63-23/actions/runs/4494122151/jobs/7906217770?pr=85) поправь
3. мы этот ПР вмержим в `main`
4. и ты в новой ветке/пулл реквесте если захочешь, сделаешь рефакторинг

что скажешь?

2023-03-23 07:49 UTC, MaksimBerezovik commented
> Максим, твой код не проходит только проверку линтеров, поэтому предложу вот что:
> 
>     1. в файл `services/webapp/hw/maksim_berezovik/lesson03.py` в строку 6 в конец её добавь комментарий: `# noqa: CCR001`
> 
>     2. [остальные замечания тут](https://github.com/alexander-sidorov/m-pt1-63-23/actions/runs/4494122151/jobs/7906217770?pr=85) поправь
> 
>     3. мы этот ПР вмержим в `main`
> 
>     4. и ты в новой ветке/пулл реквесте если захочешь, сделаешь рефакторинг
> 
> 
> что скажешь?

Принято, поправлю.

2023-03-23 08:30 UTC, MaksimBerezovik commented
Проверки линтеров все равно не проходят, mypy не ругается и black форматит.

2023-03-24 09:23 UTC, alexander-sidorov requested changes

2023-03-24 09:23 UTC, alexander-sidorov commented on services/webapp/hw/maksim_berezovik/lesson03.py
> +    default_type = ["str", "list", "dict"]  # noqa: CCR001
`CCR001` относится к функции, а не к отдельной строчке кода

2023-03-24 09:23 UTC, alexander-sidorov commented on services/webapp/hw/maksim_berezovik/lesson03.py
> +            len(req) >= 3 and req[2] == "maksim_berezovik"
сомневаюсь что дополнительный отступ был сгенерирован `black`-ом. И отчёт Github Actions это подтверждает. Нужно запустить форматирование:

`poetry run black .`

или

`task code-format`

и **закоммитить-запушить** изменения

2023-03-24 09:32 UTC, alexander-sidorov commented
> task code-lint в консоле тоже не срабатывает:

@MaksimBerezovik , это никогда и не работало на  Windows, к сожалению. Попробуй обновись с `main`, я добавил другую команду: `task windows:code-lint`, чисто для проверок

2023-03-24 13:43 UTC, MaksimBerezovik commented
Я сделал рефактор кода. Убрал все ошибки, кроме одной.
`CCR001 Cognitive complexity is too high (19 > 12)`

2023-03-27 17:23 UTC, alexander-sidorov requested changes
Максим, добавь пожалуйста `# noqa: CCR001` справа от `def view(scope):`, чтобы можно было вмержить пр

2023-03-28 18:25 UTC, MaksimBerezovik commented
> Максим, добавь пожалуйста `# noqa: CCR001` справа от `def view(scope):`, чтобы можно было вмержить пр

Готово

2023-03-28 19:05 UTC, alexander-sidorov approved these changes

2023-03-28 19:06 UTC, merged