Dmitriy Zhdanovich Lesson 5 2lvl
alexander-sidorov/m-pt1-63-23 pull request #90
Opened 2023-03-22 21:09 UTC by Mitya890625

closes #83

2023-03-26 15:09 UTC, Mitya890625 commented
Привет Саш, возникла проблема с json.loads и списком. Я его с помощью функции urllib.parse.unquote привожу к виду [a, +b, +c, +d] потом убираю с помощью replace плюсы и пытаюсь через json.loads сделать его питоническим списком однако сервак мне выдает ошибку ChunkedEncodingError. Закоментил строки с json loads чтоб ты мог убедиться что без этой функции выводиться список типа str, но не в строку, а в столбик.

2023-03-27 19:30 UTC, Mitya890625 commented
Привет, застрял на реализации метода append. При попытке вписать в URL запрос & выдает ошибку "Амперсанд (&) не разрешен". Пытался его закодировать как "%26" value_2 - пустая строка вместо значения, мб подскажешь чего-нибудь?

2023-03-28 19:37 UTC, alexander-sidorov requested changes
@Mitya890625 Митя, пожалуйста, верни мои файлы как было)

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/76160017/228348224-e4b7a380-4ec1-4670-a1f0-e397bf7cfef2.png">

2023-03-28 21:16 UTC, alexander-sidorov requested changes

2023-03-28 21:16 UTC, alexander-sidorov commented on services/webapp/hw/dmitriy_zhdanovich/lesson03.py
> +        if path == "/~/dmitriy_zhdanovich" or path == "/~/dmitriy_zhdanovich/":
этот код тоже будет перехватывать запросы на чужие адреса. Нужно вынести в самый, по возможности, верх, проверки:

_"если адрес (path) НЕ начинается на "/~/dmitriy_zhdanovich" — то сразу return None"_

2023-03-31 16:05 UTC, closed without merging